export const starData = {
	sizes: {
		Sirius: 95,
		Canopus: 95,
		Arcturus: 95,
		Vega: 95,
		Capella: 95,
		Rigel: 70,
		Procyon: 70,
		Betelgeuse: 70,
		Altair: 70,
		Aldebaran: 70,
		Spica: 70,
		Antares: 70,
		Pollux: 70,
		Fomalhaut: 70,
		Deneb: 70,
		Regulus: 70,
		Adhara: 60,
		Castor: 60,
		Gacrux: 60,
		Bellatrix: 60,
		Elnath: 60,
	},
	colors: {
		Mars: "red",
		Venus: "orange",
		Jupiter: "brown",
		Saturn: "gold",
		Sun: "yellow",
		Moon: "white",
	},
	brightStars: [
		"Sirius",
		"Canopus",
		"Arcturus",
		"Vega",
		"Capella",
		"Rigel",
		"Procyon",
		"Betelgeuse",
		"Altair",
		"Aldebaran",
		"Spica",
		"Antares",
		"Pollux",
		"Fomalhaut",
		"Deneb",
		"Regulus",
		"Adhara",
		"Castor",
		"Gacrux",
		"Bellatrix",
		"Elnath",
	],
	models: ["Jupiter", "Mars", "Moon", "Saturn", "BrightStar", "Sun", "Venus"],
};
